### ISSUE TITLE
MySql connection error ENOTFOUND

### ISSUE THREAD

**Issue by MwickFR** [typetron/typetron#12]
Hi dear Typetron Team,
First of all, thank you for the challenge you're working. Huge peace of cake ! Wish you all the best in this adventure. 👍 

As I am a student, the challenge of using your framework as a backend maybe too ambitious. _(Obviously, I hope not!)_
But I take my chance.

After, reading most of your already well-documented website, I'm dealing with a connection error.
Maybe (Almost for sure) the problem is the connection details and the package name to use.

The full error message :
```
[INFO] 22:32:15 ts-node-dev ver. 1.1.8 (using ts-node ver. 9.1.1, typescript ver. 4.1.3)
Error: getaddrinfo ENOTFOUND localhost:3306
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)
    --------------------
    at Protocol._enqueue (***\Projektor\Typetron\ProjektorBackend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (***\Projektor\Typetron\ProjektorBackend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at Connection.connect (***\Projektor\Typetron\ProjektorBackend\node_modules\mysql\lib\Connection.js:116:18)
    at new MysqlDriver (***\Projektor\Typetron\ProjektorBackend\node_modules\@typetron\Database\Drivers\MySQL\MysqlDriver.ts:34:25)
    at mysql (***\Projektor\Typetron\ProjektorBackend\config\database.ts:14:22)
    at DatabaseProvider.register (***\Projektor\Typetron\ProjektorBackend\node_modules\@typetron\Framework\Providers\DatabaseProvider.ts:20:43)
    at ***\Projektor\Typetron\ProjektorBackend\node_modules\@typetron\Framework\Application.ts:52:33
    at Array.map (<anonymous>)
    at Application.registerProviders (***\Projektor\Typetron\ProjektorBackend\node_modules\@typetron\Framework\Application.ts:50:23)
    at Application.bootstrap (***\Projektor\Typetron\ProjektorBackend\node_modules\@typetron\Framework\Application.ts:101:20)
[ERROR] 22:32:20 Error: getaddrinfo ENOTFOUND localhost:3306in SQL: "undefined"
```
My WAMP server is online and I can access to the database with PhpMyAdmin.
Here is my .env file : _(I kept the initial APP_SECRET value)_
```
APP_SECRET = f+67Sn$#O?s,U;vnPnq}{eFaYuci8Rg7@L'8&RtmAp]^By]OdBOS:?fRh^`Jx^kC
DATABASE_DRIVER = mysql
#DATABASE = database.sqlite
 DATABASE_HOST = localhost:3306
 DATABASE_USER = root
 DATABASE_PASSWORD = 
 DATABASE = projektor
```
And here is my database.ts file :
```
export default new DatabaseConfig({
    entities: './Entities',
    synchronizeSchema: true,
    migrationsDirectory: 'Database/migrations',
    seedersDirectory: 'Database/seeders',
    //driver: process.env.DATABASE_DRIVER ?? 'sqlite',
    driver: process.env.DATABASE_DRIVER ?? 'mysql',

    drivers: {
        //sqlite: () => new SqliteDriver(process.env.DATABASE ?? 'database.sqlite'),
        mysql: () => new MysqlDriver({
            host: process.env.DATABASE_HOST,
            user: process.env.DATABASE_USER,
            password: process.env.DATABASE_PASSWORD,
            database: process.env.DATABASE,
        }),
    }
})
```
Thanks for your help.
Regards.

**Comment by IonelLupu** [comment]
Hey @MwickFR. Thank you for using Typetron 🥳 . I am really excited about this 😄.


Can you try removing the port from the `DATABASE_HOST`? 

```
APP_SECRET = f+67Sn$#O?s,U;vnPnq}{eFaYuci8Rg7@L'8&RtmAp]^By]OdBOS:?fRh^`Jx^kC
DATABASE_DRIVER = mysql
#DATABASE = database.sqlite
 DATABASE_HOST = localhost
 DATABASE_USER = root
 DATABASE_PASSWORD = 
 DATABASE = projektor
```
Let me know if this works.

Don't hesitate to join the Discord channel (found on the [Typetron](https://typetron.org/) website) and ask any questions you have.

PS. I also recommend setting schema synchronization to false (`synchronizeSchema: false`) since there is a bug in MySQL with it. We are working on fixing it this week.

**Comment by MwickFR** [comment]
Straight to the point!
The error was due to the port in the expression.
Now I'm fully connected and routes are responding.

Thanks a lot !
I'll join your Discord Channel very soon.
Best Regards

**Comment by IonelLupu** [comment]
Glad I could help. Let me know your struggles so we can focus on those first. The framework should be easy to use and intuitive and only new users can help us with that 😄
